Chunk Overlap: 100
Chunk Size: 1200
Costing:
  GraphRAG: $0.0022
  GraphRAG_Evaluation: $0.0141
  RAG: $0.0009
  RAG_Evaluation: $0.0060
Embedding model (GraphRAG & RAG): text-embedding-3-small
LLM model (GraphRAG & RAG): gpt-4.1-nano
evaluation_embedding_model: text-embedding-3-small
evaluation_llm_model: gpt-4o-mini
golden_csv: golden_dataset.csv
questions: 35
timestamp: '2026-07-23 21:35:39'
